#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF4926138953E5294 (marlam@marlam.de)
#
Name     : msmtp
Version  : 1.6.6
Release  : 17
URL      : http://downloads.sourceforge.net/project/msmtp/msmtp/1.6.6/msmtp-1.6.6.tar.xz
Source0  : http://downloads.sourceforge.net/project/msmtp/msmtp/1.6.6/msmtp-1.6.6.tar.xz
Source99 : http://downloads.sourceforge.net/project/msmtp/msmtp/1.6.6/msmtp-1.6.6.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: msmtp-bin
Requires: msmtp-doc
Requires: msmtp-locales
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libidn)
BuildRequires : pkgconfig(openssl)

%description
msmtp is an SMTP client.
In the default mode, it transmits a mail to an SMTP server.

%package bin
Summary: bin components for the msmtp package.
Group: Binaries

%description bin
bin components for the msmtp package.


%package doc
Summary: doc components for the msmtp package.
Group: Documentation

%description doc
doc components for the msmtp package.


%package locales
Summary: locales components for the msmtp package.
Group: Default

%description locales
locales components for the msmtp package.


%prep
%setup -q -n msmtp-1.6.6

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489894643
export CFLAGS="$CFLAGS -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fstack-protector-strong "
export FFLAGS="$CFLAGS -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1489894643
rm -rf %{buildroot}
%make_install
%find_lang msmtp
## make_install_append content
ln -s msmtp %{buildroot}%{_bindir}/sendmail
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/msmtp
/usr/bin/sendmail

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*

%files locales -f msmtp.lang
%defattr(-,root,root,-)

